name: Go
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.11', '1.12', '1.13', '1' ]

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: go build
        run: go build -v ./...

      - name: go test
        run: go test -v ./...

      - name: go test -race
        run: go test -v -race ./...
